### PR TITLE
Color palette update

### PR DESCRIPTION
**Pull request by CodeKid0**
I did it because:
- I think this color palette looks a little better,
- My eyes hurt because of the white

Also fixed white space after footer in changelog

# Here's a before and after comparasion:

# Landing page

- Before:
image
image

- After:
image
image

# Changelog

- Before:
image

- After:
image

# Login page

- Before:
image

- After:
image

Also, i love your client. Keep up the good work. (also please merge ;D)

### CODE REVIEW

**Comment by CodeKid0** [comment]
@MineGame159 
lol

**Comment by MineGame159** [comment]
Looks good, although I don't really like the text boxes, also while you are at it, could you separate the variables from :root to two classes like .dark and .light so it could be switched with a button, if you don't want to implement the button yourself that is fine.

**Comment by CodeKid0** [comment]
> Looks good, although I don't really like the text boxes, also while you are at it, could you separate the variables from :root to two classes like .dark and .light so it could be switched with a button, if you don't want to implement the button yourself that is fine.

I'll try to implement that.

**Comment by CodeKid0** [comment]
@MineGame159 I did two different .css files because it was just easier for me. Everything should work now, test just in case.

**Comment by CodeKid0** [comment]
@MineGame159 uhh

**Comment by MineGame159** [comment]
Oh sorry, gonna look at it later today

**Comment by MineGame159** [comment]
1. Changelog page and login page (maybe more) have permanent dark mode background
2. Theme switcher button doesn't work in accounts page
3. Buttons and text boxes in accounts page have the dark mode blue tint in light mode
4. Some text is not dependant on the theme and is always dark in accounts page (capes, mc accounts)

Also I think in light mode the old background color (behind the meteor logo) looks better, dark mode is fine.

**Comment by CodeKid0** [comment]
> 1. Changelog page and login page (maybe more) have permanent dark mode background
> 
>     2. Theme switcher button doesn't work in accounts page
> 
>     3. Buttons and text boxes in accounts page have the dark mode blue tint in light mode
> 
>     4. Some text is not dependant on the theme and is always dark in accounts page (capes, mc accounts)
> 
> 
> Also I think in light mode the old background color (behind the meteor logo) looks better, dark mode is fine.

Sorry, didn't have time recently, I'll try to fix these issues today.

**Pull request closed without merging**
